### ISSUE TITLE
movie list not show in all tabs

### ISSUE THREAD

**Issue by khem88** [aaronoe/FlutterCinematic#10]
Hi,

        It show the bellow message in the app

           "Sorry, there was an error loading your movie"

  Thanks

**Comment by prasant10050** [comment]
i have face same error..

**Comment by aaronoe** [comment]
Hi @khem88 and @prasant10050 ,
The app wasn't fully functional with dart2 until now. I just merged a port which also removes all the `new` keywords, which should make the code more readable for you :smile: Just check out `master` and try to run it again

**Comment by prasant10050** [comment]
Congrats for design this app..its very beneficial for making app by flutter.

Ok..I will to run the app..

**Comment by hasonguo** [comment]
Hi,
  I had checked out the newest code. My dart version is dart 2.
  But It still show the bellow message in the app

       "Sorry, there was an error loading the data!"
Thanks
